server:
  port: 12345

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kopring
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      file: ./docker/docker-compose.yml
      lifecycle-management: start_and_stop
      # Temporarily disable due to a bug, will be fixed in Boot 3.1.6 or 3.2.0
      # https://github.com/spring-projects/spring-boot/issues/37982
      enabled: false

infcon:
  location: coex
  date: 2023-08-15
  url: https://inflearn.com/conf/infcon-2023
